mongoDatabase:
  url: mongodb://127.0.0.1:27017/dropwizard?maxPoolSize=200

server:
  rootPath: /dropwizard/*
  adminContextPath: /dropwizard/admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

documentation:
  resourcePackage: com.iroshnk.dropwizardmongo.resources

jerseyClient :
    minThreads : 1
    maxThreads : 2
    workQueueSize : 8
    gzipEnabled : true
    gzipEnabledForRequests : true
    chunkedEncodingEnabled : true

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  appenders:
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/dropwizard.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/archive-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC
